### ISSUE TITLE
Chemical Protective/Defender Chest Clashing with TACZ animations - Minor

### ISSUE THREAD

**Issue by DurpyFlabergazm** [LesRaisins-Studios/LesRaisinsArmor#2]
![2024-07-13_19 02 31](https://github.com/user-attachments/assets/3eb436c2-327b-4e37-8832-4f4173644d9d)
![2024-07-13_19 02 40](https://github.com/user-attachments/assets/a78b72bf-6c50-4aeb-b71b-1c8c308ce645)
![2024-07-13_18 59 55](https://github.com/user-attachments/assets/2ad3e172-14d2-48a0-8787-109d01479c46)
![2024-07-13_19 02 16](https://github.com/user-attachments/assets/fa6e8ff0-a17b-4f12-97d1-ee1332c7b6a2)

TACZ (Timeless and Classics Zero). Arm detaches from body. Nothing major but when tested each of your chest models in game it was only the Chem Protective and Defender Chest pieces acted weird in this manner (using 3rd person). Would appreciate the fix for detail. (Especially for multiplayer experiences)

Other Modded Chest Pieces work just fine. Even your other chest models... just the two above.
You can even see the arm where my character model is in the above images as well

Maybe it's a matter of where the models are attached to player model Idk.
Currently Using Occulus

Forge - 47.3.0
Using: 
Irarmor-0.1.1
tacz-1.0.2-release

**Comment by xjqsh** [comment]
It looks like there's something wrong with the pivot point of the model. I'll fix it later.

**Comment by xjqsh** [comment]
![QQ_1721288906760](https://github.com/user-attachments/assets/200cdea4-88e4-41ae-bb39-3375a27f9e75)
![QQ_1721288974776](https://github.com/user-attachments/assets/83b393e1-228b-4270-8589-980a6b25b847)
fixed, will upload to curseforge later.
