### ISSUE TITLE
You can see the edges of the character in the easynpcs and in EpicFight mode

### ISSUE THREAD

**Issue by yHenriTopper** [LesRaisins-Studios/LesRaisinsArmor#5]
What's up friend, I don't know if this has happened to anyone else but when I use the armor, I can see the edges of my body, they are left uncovered.

 

[https://imgur.com/ee54hk4](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fee54hk4)

 

It doesn't just happen to me, when I want to put the armor on the NPCS of the Easy NPCS mod, the same thing happens to them, the edges of their body are protruding from the armor

 

[https://imgur.com/a/BXMrVoV](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fa%252fBXMrVoV)

 

I hope there is a solution for this, thank you very much for the excellent work, they are the most elaborate armors I have seen.

 

[https://imgur.com/undefined](https://legacy.curseforge.com/linkout?remoteUrl=https%253a%252f%252fimgur.com%252fundefined)

**Comment by xjqsh** [comment]
try this. i've tried do some simple compat with epicfight. https://github.com/LesRaisins-Studios/LesRaisinsArmor/releases/tag/beta  
It may not be perfect, but it should be much better.

**Comment by yHenriTopper** [comment]
it doesn't work bro, it doesn't work alone, not with epicfight, not with current geckolib, not with current forge, not just

**Comment by xjqsh** [comment]
damn, stupid mixin problem while packing. I forgot to try it without dev env. Let me upload a new one. this should work i think. https://github.com/LesRaisins-Studios/LesRaisinsArmor/releases/download/beta/lrarmor-1.20.1-0.1.4.1-beta-2.jar  

https://github.com/user-attachments/assets/1e712e12-e7de-4eee-8854-3dae266f6fbd

**Comment by xjqsh** [comment]
some suit need re-config, i will do that before release, or you can find the config file under `assets/lrarmor/armor_display` in the jar and adjust yourself at this moment. ref https://github.com/LesRaisins-Studios/LesRaisinsArmor/tree/1.20.1/src/main/resources/assets/lrarmor/armor_display

**Comment by yHenriTopper** [comment]
If it works for me, it looks good brother, the latest versions of Epicfight make it compatible with armor from other mods, one of the ones I saw is yours, it just seemed strange to me, and it still seems strange to me because half of the arms it shows, when you put your armor on the npcs of EASYNPC and CUSTOMNPC

**Comment by yHenriTopper** [comment]
The mod is well done, I like how it looks, thank you very much for such a great wonder

**Comment by xjqsh** [comment]
try this. https://github.com/LesRaisins-Studios/LesRaisinsArmor/releases/download/0.1.4.2-beta/lrarmor-1.20.1-0.1.4.2-beta.jar  
I've tried to compat wirh all the sub class of humanoid models, include npcs from esay npc, vanilla zombie/skeleton and epic fight zombie/skeleton  
So far it looks ok, however as I don't play either mod so I'm not sure if there are any potential issues

**Comment by yHenriTopper** [comment]
![2024-09-01_03 01 12](https://github.com/user-attachments/assets/fe3ceca1-f455-465b-a251-4c07fa8cebcd)

wow, that's it, solved with the npcs of the EASY NPC, thank you very much friend

**Comment by yHenriTopper** [comment]
![2024-08-29_06 42 10](https://github.com/user-attachments/assets/b571ac5b-48eb-47bf-929b-c69a51b31128)
This is an image from when it was incompatible before
